name: queues
on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

permissions:
  contents: write  

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: fetch
        run: |
          format() {
            local region=$1
            local response
            response=$(curl -s "https://api.deadbyqueue.com/queuetime?region=$region")
            echo "$response" | sed -e 's/Killer: //g' -e 's/Survivor: //g' -e 's/ | /\//g'
          }
          
          FRANKFURT=$(format "eu-central-1")
          DUBLIN=$(format "eu-west-1")
          LONDON=$(format "eu-west-2")
          
          echo "Queue Times: 🇩🇪 $FRANKFURT • 🇮🇪 $DUBLIN • 🇬🇧 $LONDON" > queue

      - name: commit
        run: |
          git config --global user.name "queues"
          git config --global user.email "queue@queue.com"
          git add queue
          git commit -m "update" || exit 0
          git push
